#pragma once

#include "driver/gpio.h"
#include "driver/uart.h"

#define APP_BASE_PATH "/web"
#define APP_STORAGE_PARTITION_LABEL "storage"
#define APP_WEB_CONFIG_PATH "/config"
#define APP_WEB_AUTH_USERNAME "admin"
#define APP_WEB_AUTH_PASSWORD "123456"
#define APP_WEB_AUTH_BASIC "Basic YWRtaW46MTIzNDU2"
#define APP_WEB_AUTH_REALM "iothub-config"
#define APP_SCRATCH_SIZE 4096
#define APP_JSON_BUFFER_SIZE 4096
#define APP_OTA_REBOOT_DELAY_MS 1500
#define APP_FLASH_SECTOR_SIZE 4096
#define APP_FACTORY_RESET_BOOT_GPIO GPIO_NUM_0
#define APP_FACTORY_RESET_HOLD_MS 5000
#define APP_FACTORY_RESET_POLL_MS 100

#define RELAY_DEFAULT_GPIO GPIO_NUM_16
#define LED_DEFAULT_GPIO GPIO_NUM_27
#define INPUT_DEFAULT_GPIO GPIO_NUM_33
#define UART_PORT UART_NUM_1
#define UART_RX_GPIO GPIO_NUM_18
#define UART_TX_GPIO GPIO_NUM_17
#define UART_PARITY_PROBE_TIME_MS 250
#define UART_LOW_BAUD_THRESHOLD 4800
#define UART_LOW_BAUD_PROBE_TIME_MS 1000
#define UART_RX_BUFFER_SIZE 2048
#define UART_SAMPLE_BUFFER_SIZE 256
#define UART_CONSOLE_PLAIN_SIZE 1024
#define UART_CONSOLE_HEX_SIZE 3072
#define UART_TX_BUFFER_SIZE 256
#define UART_TX_PREVIEW_SIZE 192
#define UART_TX_HEX_TEXT_SIZE 256
#define UART_PROBE_RESULT_MAX 6
#define UART_MANUAL_CANDIDATE_MAX 24

#define WIFI_SCAN_LIST_SIZE 8
#define APP_WIFI_PROFILE_MAX 5

#define BT_MODE_OFF 0
#define BT_MODE_BLE 1
#define BT_MODE_SPP 2

#define NET_MODE_AP 0
#define NET_MODE_STA 1
#define NET_MODE_APSTA 2
